version: '3.8'
services:
  opentutor:
    container_name: gameifai-client
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  cypress:
    container_name: cypress
    depends_on:
      - gameifai-client
    build:
      context: cypress
    environment:
      - "CYPRESS_BASE_URL=http://gameifai/"
      - "CYPRESS_SNAPSHOT_DIFF_DIR=/app/cypress/snapshots/snapshot_failed_diffs"
