version: '3.8'
services:
  gameifai:
    container_name: gameifai
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_JUPYTER_SERVER_HTTP_URL=https://jupyter-dev.gameifai.org/api/jupyter/
      - REACT_APP_JUPYTER_SERVER_WS_URL=https://jupyter-dev.gameifai.org/api/jupyter/
      - REACT_APP_JUPYTER_SERVER_TOKEN=${REACT_APP_JUPYTER_SERVER_TOKEN}
  # cypress:
  #   container_name: cypress
  #   depends_on:
  #     - gameifai
  #   build:
  #     context: cypress
  #   environment:
  #     - "CYPRESS_BASE_URL=http://gameifai/"
  #     - "CYPRESS_SNAPSHOT_DIFF_DIR=/app/cypress/snapshots/snapshot_failed_diffs"
