version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # to use node 18:
      - n 18 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490
      - NODE_ENV=dev yarn install 
      - (cd client && yarn install --frozen-lockfile)
  pre_build:
    on-failure: ABORT # or CONTINUE
    commands:
      - npm run test:format
      - npm run test:license
      - cd client
      - npm run test:lint
      # - npm run test:types

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
