name: test and publish
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.13"
      - name: Install
        run:  yarn install
      - name: Run format test
        run: yarn run test:format
      - name: Run license test
        run: npm run test:license
      - name: Client - Install
        run: cd client && yarn install
      - name: Client - Run lint test
        run: cd client && yarn run test:lint
      - name: Client - Run types test
        run: cd client && yarn run test:types